import type { Metadata } from "next";
import "./globals.css";
import Footer from "./components/footer/Footer";
import NextTopLoader from 'nextjs-toploader';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div style={{minHeight:"71vh"}}>
        <NextTopLoader color="red"/>

        {children}

        </div>
        <Footer/>
      </body>
    </html>
  );
}
